const CFG = window.APP_CONFIG;
const state = { token:'', user:null, records:[], reviewRecord:null, users:[] };
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast show'+(error?' error':'');setTimeout(()=>el.className='toast',3000)}
function roleName(role){return ({teacher:'教師',admin:'系統管理者',academic:'教務主任',student_affairs:'學務主任',general_affairs:'總務主任',counseling:'輔導主任',principal:'校長'})[role]||role}
function deptForRole(role){return ({academic:'academic',student_affairs:'student_affairs',general_affairs:'general_affairs',counseling:'counseling',principal:'principal'})[role]||''}
function deptName(k){return ({academic:'教務處',student_affairs:'學務處',general_affairs:'總務處',counseling:'輔導處',principal:'校長'})[k]||k}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('zh-TW').format(d)}
async function api(action,payload={}){if(!CFG.GAS_URL||CFG.GAS_URL.includes('請貼上'))throw new Error('請先在 config.js 設定 GAS_URL');const r=await fetch(CFG.GAS_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:state.token,...payload})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('後端回傳格式錯誤：'+text.slice(0,120))}if(!data.ok)throw new Error(data.error||'操作失敗');return data}
async function login(username,password){const d=await api('login',{username,password});state.token=d.token;state.user=d.user;sessionStorage.setItem('meetingToken',state.token);sessionStorage.setItem('meetingUser',JSON.stringify(state.user));showApp();await loadRecords();if(state.user.mustChangePassword)openPasswordDialog(true)}
async function resumeSession(){const token=sessionStorage.getItem('meetingToken');const raw=sessionStorage.getItem('meetingUser');if(!token||!raw)return;try{state.token=token;state.user=JSON.parse(raw);await api('listRecords',{filters:{}});showApp();await loadRecords();if(state.user.mustChangePassword)openPasswordDialog(true)}catch(e){clearSession()}}
function clearSession(){state.token='';state.user=null;sessionStorage.removeItem('meetingToken');sessionStorage.removeItem('meetingUser');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
async function logout(){try{if(state.token)await api('logout')}catch{}clearSession()}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=state.user.name||state.user.username;$('#userRole').textContent=roleName(state.user.role);const elevated=state.user.role!=='teacher';$('#adminTab').classList.toggle('hidden',!elevated);$('#usersTab').classList.toggle('hidden',state.user.role!=='admin');$('#newBtn').classList.toggle('hidden',!['teacher','admin'].includes(state.user.role));$('#newRecordTab').classList.toggle('hidden',!['teacher','admin'].includes(state.user.role));$('#filterGrade').disabled=state.user.role==='teacher';if(state.user.role==='teacher'){$('#filterGrade').value=state.user.grade;$('#grade').value=state.user.grade;$('#grade').disabled=true}else $('#grade').disabled=false;$('#filterYear').value=CFG.DEFAULT_SCHOOL_YEAR||115;$('#adminYear').value=CFG.DEFAULT_SCHOOL_YEAR||115;}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id))}
async function loadRecords(){try{const filters={schoolYear:$('#filterYear').value,semester:$('#filterSemester').value,grade:$('#filterGrade').value};const d=await api('listRecords',{filters});state.records=d.records||[];renderRecords(state.records,'#recordList',false)}catch(e){toast(e.message,true)}}
async function loadAdmin(){try{const filters={schoolYear:$('#adminYear').value,grade:$('#adminGrade').value};const d=await api('listRecords',{filters});renderRecords(d.records||[],'#adminList',true)}catch(e){toast(e.message,true)}}
function renderRecords(records,target,admin){const el=$(target);if(!records.length){el.innerHTML='<div class="empty">目前沒有符合條件的會議紀錄</div>';return}el.innerHTML=records.map(r=>`<article class="record-card"><div><h3>${esc(r.schoolYear)}學年度第${esc(r.semester)}學期・${esc(r.grade)}年級・第${esc(r.meetingNo)}次學年會議 <span class="status-chip">${r.status==='submitted'?'已送出':'草稿'}</span></h3><p>${esc(fmtDate(r.meetingDate))} ${esc(r.meetingTime||'')}｜${esc(r.location||'')}｜主席：${esc(r.chair||'')}</p><p>最後更新：${esc(r.updatedAt||'')} ${r.updatedByName?'｜'+esc(r.updatedByName):''}</p></div><div class="record-actions"><button class="btn ghost" onclick="openReview('${r.id}')">檢視${admin?' / 回覆':''}</button>${r.canEdit?`<button class="btn secondary" onclick="editRecord('${r.id}')">編修</button>`:''}<button class="btn ghost" onclick="downloadSingle('${r.id}')">PDF</button></div></article>`).join('')}
function blankForm(){ $('#recordForm').reset();$('#recordId').value='';$('#schoolYear').value=CFG.DEFAULT_SCHOOL_YEAR||115;$('#semester').value='1';if(state.user?.role==='teacher')$('#grade').value=state.user.grade;$('#editorTitle').textContent='新增學年會議紀錄';$('#existingPhotos').innerHTML=''}
function newRecord(){blankForm();switchView('editorView')}
async function editRecord(id){try{const d=await api('getRecord',{id});fillForm(d.record);switchView('editorView')}catch(e){toast(e.message,true)}}
function fillForm(r){const map={recordId:'id',schoolYear:'schoolYear',semester:'semester',grade:'grade',meetingNo:'meetingNo',meetingDate:'meetingDate',meetingTime:'meetingTime',chair:'chair',recorder:'recorder',location:'location',attendees:'attendees',agenda:'agenda',discussion:'discussion'};Object.entries(map).forEach(([id,k])=>$('#'+id).value=r[k]||'');$('#editorTitle').textContent='編修學年會議紀錄';renderExistingPhotos(r.photos||[])}
function renderExistingPhotos(photos){$('#existingPhotos').innerHTML=photos.map(p=>`<div><img src="${esc(p.url)}" alt="會議照片"><div>${esc(p.caption||'')}</div></div>`).join('')}
async function fileToData(file){if(!file)return null;if(file.size>5*1024*1024)throw new Error('單張圖片請控制在 5MB 以內');return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve({name:file.name,mimeType:file.type||'application/octet-stream',base64:String(rd.result).split(',')[1]});rd.onerror=reject;rd.readAsDataURL(file)})}
async function collectForm(status){const photos=[];for(const inp of $$('.meetingPhoto')){const i=Number(inp.dataset.index);if(inp.files[0]){const f=await fileToData(inp.files[0]);photos.push({...f,caption:$$('.photoCaption').find(x=>Number(x.dataset.index)===i)?.value||'',sort:i+1})}}return {id:$('#recordId').value,schoolYear:$('#schoolYear').value,semester:$('#semester').value,grade:$('#grade').value,meetingNo:$('#meetingNo').value,meetingDate:$('#meetingDate').value,meetingTime:$('#meetingTime').value,chair:$('#chair').value.trim(),recorder:$('#recorder').value.trim(),location:$('#location').value.trim(),attendees:$('#attendees').value.trim(),agenda:$('#agenda').value.trim(),discussion:$('#discussion').value.trim(),status,attendanceImage:await fileToData($('#attendanceImage').files[0]),photos}}
async function saveRecord(status){try{const payload=await collectForm(status);if(!payload.schoolYear||!payload.grade||!payload.meetingNo||!payload.meetingDate)throw new Error('請完成必要欄位');const d=await api('saveRecord',{record:payload});toast(status==='submitted'?'已存檔送出':'草稿已儲存');$('#recordId').value=d.id;await loadRecords();switchView('recordsView')}catch(e){toast(e.message,true)}}
async function openReview(id){try{const d=await api('getRecord',{id});state.reviewRecord=d.record;const r=d.record;$('#reviewMeta').textContent=`${r.schoolYear}學年度第${r.semester}學期｜${r.grade}年級｜第${r.meetingNo}次`;$('#reviewContent').innerHTML=`<div class="review-block"><h4>基本資料</h4><div class="box">時間：${esc(r.meetingDate)} ${esc(r.meetingTime)}\n地點：${esc(r.location)}\n主席：${esc(r.chair)}\n會議記錄：${esc(r.recorder)}\n出席者：${esc(r.attendees)}</div></div><div class="review-block"><h4>報告事項與討論議題</h4><div class="box">${esc(r.agenda)}</div></div><div class="review-block"><h4>會議記錄／議題討論</h4><div class="box">${esc(r.discussion)}</div></div><div class="review-block"><h4>處室回覆</h4><div class="reply-grid">${['academic','student_affairs','general_affairs','counseling','principal'].map(k=>`<div class="reply-pill"><strong>${deptName(k)}</strong>${esc(r.replies?.[k]||'尚未回覆')}</div>`).join('')}</div></div>`;const dept=deptForRole(state.user.role);const canReply=!!dept||state.user.role==='admin';$('.reply-box').classList.toggle('hidden',!canReply);if(canReply){if(state.user.role==='admin'){let sel=$('#adminReplyDept');if(!sel){sel=document.createElement('select');sel.id='adminReplyDept';sel.innerHTML=['academic','student_affairs','general_affairs','counseling','principal'].map(k=>`<option value="${k}">${deptName(k)}</option>`).join('');$('#replyText').parentElement.prepend(sel)}sel.classList.remove('hidden');$('#replyText').value=r.replies?.[sel.value]||'';sel.onchange=()=>$('#replyText').value=r.replies?.[sel.value]||''}else{$('#adminReplyDept')?.classList.add('hidden');$('#replyText').value=r.replies?.[dept]||''}}$('#reviewDialog').showModal()}catch(e){toast(e.message,true)}}
async function saveReply(){try{const department=state.user.role==='admin'?$('#adminReplyDept').value:deptForRole(state.user.role);await api('saveReply',{recordId:state.reviewRecord.id,department,text:$('#replyText').value.trim()});toast('回覆已儲存');$('#reviewDialog').close();await openReview(state.reviewRecord.id)}catch(e){toast(e.message,true)}}
function base64ToDownload(base64,mime,name){const a=document.createElement('a');a.href=`data:${mime};base64,${base64}`;a.download=name;document.body.appendChild(a);a.click();a.remove()}
async function downloadSingle(id){try{toast('正在產生 PDF…');const d=await api('exportSinglePdf',{id});base64ToDownload(d.base64,'application/pdf',d.fileName)}catch(e){toast(e.message,true)}}
async function exportYear(){try{const schoolYear=$('#filterYear').value,grade=$('#filterGrade').value,semester=$('#filterSemester').value;if(!schoolYear||!grade)throw new Error('請先指定學年度與學年');toast('正在彙整學年 PDF…');const d=await api('exportYearPdf',{filters:{schoolYear,grade,semester}});base64ToDownload(d.base64,'application/pdf',d.fileName)}catch(e){toast(e.message,true)}}
function openPasswordDialog(force=false){$('#passwordForm').reset();$('#passwordHint').textContent=force?'首次登入必須先修改初始密碼，完成後才能繼續使用。':'請輸入目前密碼與新密碼。';$('#closePassword').classList.toggle('hidden',force);$('#passwordDialog').dataset.force=force?'1':'0';$('#passwordDialog').showModal()}
async function changePassword(){const cur=$('#currentPassword').value,neu=$('#newPassword').value,confirm=$('#confirmPassword').value;if(neu!==confirm)throw new Error('兩次輸入的新密碼不一致');const d=await api('changePassword',{currentPassword:cur,newPassword:neu});state.user=d.user;sessionStorage.setItem('meetingUser',JSON.stringify(state.user));$('#passwordDialog').close();toast('密碼已更新')}
async function loadUsers(){try{const d=await api('listUsers');state.users=d.users||[];renderUsers()}catch(e){toast(e.message,true)}}
function renderUsers(){const el=$('#userList');if(!state.users.length){el.innerHTML='<div class="empty">尚未建立帳號</div>';return}el.innerHTML=state.users.map(u=>`<article class="user-card"><div><div class="user-title"><strong>${esc(u.name)}</strong><code>${esc(u.username)}</code>${u.active?'':'<span class="status-chip off">已停用</span>'}${u.mustChangePassword?'<span class="status-chip warn">待改密碼</span>':''}</div><p>${esc(roleName(u.role))}${u.grade?'｜'+esc(u.grade)+'年級':''}｜最近登入：${esc(u.lastLoginAt||'尚未登入')}</p></div><div class="record-actions"><button class="btn secondary" onclick="editUser('${esc(u.username)}')">編輯</button><button class="btn ghost" onclick="quickReset('${esc(u.username)}')">重設密碼</button><button class="btn ghost" onclick="toggleUser('${esc(u.username)}',${u.active?'false':'true'})">${u.active?'停用':'啟用'}</button></div></article>`).join('')}
function openUserDialog(user=null){$('#userForm').reset();$('#accountActive').checked=true;$('#editUsernameOriginal').value=user?.username||'';$('#accountUsername').value=user?.username||'';$('#accountUsername').disabled=!!user;$('#accountName').value=user?.name||'';$('#accountRole').value=user?.role||'teacher';$('#accountGrade').value=user?.grade||'1';$('#accountActive').checked=user?!!user.active:true;$('#accountPassword').required=!user;$('#userDialogTitle').textContent=user?'編輯帳號':'新增帳號';syncGradeVisibility();$('#userDialog').showModal()}
function syncGradeVisibility(){$('#accountGradeWrap').classList.toggle('hidden',$('#accountRole').value!=='teacher')}
function editUser(username){const u=state.users.find(x=>x.username===username);if(u)openUserDialog(u)}
async function saveUserFromForm(){const user={username:$('#accountUsername').value.trim(),name:$('#accountName').value.trim(),role:$('#accountRole').value,grade:$('#accountGrade').value,active:$('#accountActive').checked,password:$('#accountPassword').value};await api('saveUser',{user});$('#userDialog').close();toast('帳號已儲存');await loadUsers()}
async function quickReset(username){const p=prompt(`請輸入 ${username} 的新密碼（至少 8 碼，需含英文字母與數字）：`);if(p===null)return;try{await api('resetPassword',{username,newPassword:p});toast('密碼已重設，該帳號下次登入會要求修改密碼');await loadUsers()}catch(e){toast(e.message,true)}}
async function toggleUser(username,active){try{await api('setUserActive',{username,active});toast(active?'帳號已啟用':'帳號已停用');await loadUsers()}catch(e){toast(e.message,true)}}
window.openReview=openReview;window.editRecord=editRecord;window.downloadSingle=downloadSingle;window.editUser=editUser;window.quickReset=quickReset;window.toggleUser=toggleUser;
window.addEventListener('load',()=>{$('#loginForm').onsubmit=async e=>{e.preventDefault();try{$('#loginBtn').disabled=true;await login($('#loginUsername').value.trim(),$('#loginPassword').value)}catch(err){toast(err.message,true)}finally{$('#loginBtn').disabled=false}};$('#logoutBtn').onclick=logout;$('#changePasswordBtn').onclick=()=>openPasswordDialog(false);$$('.tab').forEach(t=>t.onclick=()=>{switchView(t.dataset.view);if(t.dataset.view==='adminView')loadAdmin();if(t.dataset.view==='usersView')loadUsers()});$('#newBtn').onclick=newRecord;$('#newRecordTab').onclick=()=>{blankForm();switchView('editorView')};$('#backBtn').onclick=()=>switchView('recordsView');$('#saveDraftBtn').onclick=()=>saveRecord('draft');$('#submitBtn').onclick=()=>saveRecord('submitted');$('#searchBtn').onclick=loadRecords;$('#adminSearchBtn').onclick=loadAdmin;$('#exportYearBtn').onclick=exportYear;$('#closeReview').onclick=()=>$('#reviewDialog').close();$('#saveReplyBtn').onclick=saveReply;$('#exportSingleBtn').onclick=()=>downloadSingle(state.reviewRecord.id);$('#closePassword').onclick=()=>{if($('#passwordDialog').dataset.force!=='1')$('#passwordDialog').close()};$('#passwordForm').onsubmit=async e=>{e.preventDefault();try{await changePassword()}catch(err){toast(err.message,true)}};$('#newUserBtn').onclick=()=>openUserDialog();$('#closeUserDialog').onclick=()=>$('#userDialog').close();$('#accountRole').onchange=syncGradeVisibility;$('#userForm').onsubmit=async e=>{e.preventDefault();try{await saveUserFromForm()}catch(err){toast(err.message,true)}};resumeSession()});
